/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuahangbanpizza.GUI;

/**
 *
 * @author DELL
 */
public class ThemKH extends javax.swing.JFrame {

    /**
     * Creates new form XuatDanhSachKH
     */
    public ThemKH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        SDTTextField = new javax.swing.JTextField();
        tenTextField = new javax.swing.JTextField();
        ngaySinhLabel = new javax.swing.JLabel();
        nuRadioButton = new javax.swing.JRadioButton();
        HoTextField = new javax.swing.JTextField();
        MaLabel = new javax.swing.JLabel();
        gioiTinhLabel = new javax.swing.JLabel();
        diaChiLabel = new javax.swing.JLabel();
        SDTLabel = new javax.swing.JLabel();
        MaTextField = new javax.swing.JTextField();
        hoLabel = new javax.swing.JLabel();
        ngaySinhTextField = new javax.swing.JTextField();
        diaChiTextField = new javax.swing.JTextField();
        tenLabel = new javax.swing.JLabel();
        namRadioButton = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        exitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("THÊM KHÁCH HÀNG");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 6, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, 406, 10));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SDTTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SDTTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(SDTTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 157, 311, -1));

        tenTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(tenTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 67, 311, -1));

        ngaySinhLabel.setText("Ngày sinh");
        jPanel3.add(ngaySinhLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 126, 89, 24));

        nuRadioButton.setText("Nữ");
        jPanel3.add(nuRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 98, 98, -1));

        HoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(HoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 37, 311, -1));

        MaLabel.setText("Mã khách hàng");
        jPanel3.add(MaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 89, 24));

        gioiTinhLabel.setText("Giới tính");
        jPanel3.add(gioiTinhLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, 89, 24));

        diaChiLabel.setText("Địa chỉ");
        jPanel3.add(diaChiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 186, 89, 24));

        SDTLabel.setText("Số điện thoại");
        jPanel3.add(SDTLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 156, 89, 24));

        MaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(MaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 7, 311, -1));

        hoLabel.setText("Họ ");
        jPanel3.add(hoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 36, 89, 24));

        ngaySinhTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngaySinhTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(ngaySinhTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 127, 311, -1));
        jPanel3.add(diaChiTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 187, 311, -1));

        tenLabel.setText("Tên");
        jPanel3.add(tenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 66, 89, 24));

        namRadioButton.setText("Nam");
        namRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namRadioButtonActionPerformed(evt);
            }
        });
        jPanel3.add(namRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 98, 98, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 412, 10));

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel4.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 22, -1, -1));

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel4.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 22, -1, -1));

        addButton.setText("Add");
        jPanel4.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 22, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoTextFieldActionPerformed

    private void MaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaTextFieldActionPerformed

    private void tenTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenTextFieldActionPerformed

    private void namRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namRadioButtonActionPerformed

    private void SDTTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SDTTextFieldActionPerformed
//         TODO add your handling code here:
    }//GEN-LAST:event_SDTTextFieldActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButtonActionPerformed

    private void ngaySinhTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngaySinhTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngaySinhTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemKH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HoTextField;
    private javax.swing.JLabel MaLabel;
    private javax.swing.JTextField MaTextField;
    private javax.swing.JLabel SDTLabel;
    private javax.swing.JTextField SDTTextField;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel diaChiLabel;
    private javax.swing.JTextField diaChiTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel gioiTinhLabel;
    private javax.swing.JLabel hoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton namRadioButton;
    private javax.swing.JLabel ngaySinhLabel;
    private javax.swing.JTextField ngaySinhTextField;
    private javax.swing.JRadioButton nuRadioButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel tenLabel;
    private javax.swing.JTextField tenTextField;
    // End of variables declaration//GEN-END:variables
}
